### ISSUE TITLE
Bitbucket compatibility

### ISSUE THREAD

**Issue by d-miketa** [LaurenceWarne/prefab.el#1]
Hi and thanks for the plugin! I'd like to use it but I often work with cookiecutters that live on Bitbucket and are regularly updated. Unfortunately I haven't figured out how to use a Bitbucket-hosted cookiecutter with `prefab` (e.g. https://bitbucket.org/exolever/service-cookiecutter-template/src/master/ fails). Seems like Bitbucket may be incompatible with the way you pull cookiecutters?

Also, would it be possible to add an optional argument to `prefab` to specify the template out right?

Thank you! :)

**Comment by LaurenceWarne** [comment]
Hi thanks for the report.  I can reproduce, but for that template strangley I cannot pull through the `cookiecutter` cli either:
```
cookiecutter.exceptions.VCSNotInstalled: 'hg' is not installed.
```
So it seems to have wrongly been identified as using `hg` rather than `git`.  Are you able to pull it through the cookiecutter cli (I'm using cookiecutter `2.1.1`)?

> Also, would it be possible to add an optional argument to prefab to specify the template out right?

As in an optional argument to `prefab` like `(prefab "my-cool-template")`?  Seems a good idea :slightly_smiling_face:

**Comment by LaurenceWarne** [comment]
Also, is an error signalled by `prefab` when you try to pull that template (I've just pushed a small commit which fixed some errors from cookiecutter not being recognised as such, maybe that will help)?

**Comment by d-miketa** [comment]
That small fix did it!

There were actually two issues:
1. re-downloading templates hanging on yes/no (now fixed)
2. Github and BB have different Cookiecutter patterns, e.g. with BB you should do `cookiecutter git@bitbucket.org:exolever/service-cookiecutter-template.git`

Thank you! :)

**Comment by LaurenceWarne** [comment]
Nice, I've also just pushed: https://github.com/LaurenceWarne/prefab.el/commit/5ca61a420d8de5e3707a5c2f01153f4ab2ea3ec1 so `prefab` now accepts templates to be passed as parameters :slightly_smiling_face:
